create extension if not exists vector;
create extension if not exists pgcrypto;

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  author text,
  tarot_system text,
  publication_year integer,
  public_domain boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.knowledge_chunks (
  id bigint generated by default as identity primary key,
  book_id uuid not null references public.books(id) on delete cascade,
  chunk_index integer not null,
  content text not null,
  chapter text,
  card_name text,
  section_type text,
  token_estimate integer,
  embedding vector(1536) not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (book_id, chunk_index)
);

create index if not exists knowledge_chunks_book_id_idx
  on public.knowledge_chunks (book_id);

create index if not exists knowledge_chunks_card_name_idx
  on public.knowledge_chunks (card_name);

create index if not exists knowledge_chunks_embedding_hnsw
  on public.knowledge_chunks
  using hnsw (embedding vector_cosine_ops);

alter table public.books enable row level security;
alter table public.knowledge_chunks enable row level security;

create or replace function public.match_knowledge_chunks(
  query_embedding vector(1536),
  match_count integer default 8,
  filter_tarot_system text default null
)
returns table (
  id bigint,
  book_id uuid,
  book_title text,
  author text,
  tarot_system text,
  chunk_index integer,
  content text,
  chapter text,
  card_name text,
  section_type text,
  similarity double precision
)
language sql
stable
as $$
  select
    kc.id,
    kc.book_id,
    b.title as book_title,
    b.author,
    b.tarot_system,
    kc.chunk_index,
    kc.content,
    kc.chapter,
    kc.card_name,
    kc.section_type,
    1 - (kc.embedding <=> query_embedding) as similarity
  from public.knowledge_chunks kc
  join public.books b on b.id = kc.book_id
  where filter_tarot_system is null or b.tarot_system = filter_tarot_system
  order by kc.embedding <=> query_embedding
  limit greatest(1, least(match_count, 20));
$$;

revoke all on function public.match_knowledge_chunks(vector, integer, text) from public;
revoke all on function public.match_knowledge_chunks(vector, integer, text) from anon;
revoke all on function public.match_knowledge_chunks(vector, integer, text) from authenticated;
grant execute on function public.match_knowledge_chunks(vector, integer, text) to service_role;
